import {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BarChart3,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Code2,
  Compass,
  CreditCard,
  Crown,
  Database,
  Download,
  Edit,
  Edit3,
  Eye,
  FileCheck,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  Globe,
  GraduationCap,
  Grid3X3,
  Headset,
  HelpCircle,
  History,
  Home,
  Inbox,
  Info,
  Key,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Minus,
  Moon,
  Network,
  Percent,
  PieChart,
  Play,
  Plus,
  PlusCircle,
  Printer,
  Quote,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  Search,
  Send,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  Users,
  Wand2,
  X,
  XCircle,
  Zap,
} from 'lucide';

/** `[tag, attributes]` pairs, exactly the shape lucide ships. */
export type IconNode = readonly (readonly [string, Record<string, string | number>])[];

/**
 * Brand marks: lucide v1 moved these out of the core set, so they are inlined
 * here with the same 24x24 grid the rest of the icons use.
 */
const Facebook: IconNode = [
  ['path', { d: 'M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z' }],
];
const Github: IconNode = [
  ['path', { d: 'M15 22v-4a4.8 4.8 0 0 0-1-3.5c3 0 6-2 6-5.5.08-1.25-.27-2.48-1-3.5.28-1.15.28-2.35 0-3.5 0 0-1 0-3 1.5-2.64-.5-5.36-.5-8 0C6 2 5 2 5 2c-.3 1.15-.3 2.35 0 3.5A5.403 5.403 0 0 0 4 9c0 3.5 3 5.5 6 5.5-.39.49-.68 1.05-.85 1.65-.17.6-.22 1.23-.15 1.85v4' }],
  ['path', { d: 'M9 18c-4.51 2-5-2-7-2' }],
];
const Linkedin: IconNode = [
  ['path', { d: 'M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z' }],
  ['rect', { width: '4', height: '12', x: '2', y: '9' }],
  ['circle', { cx: '4', cy: '4', r: '2' }],
];
const Twitter: IconNode = [
  ['path', { d: 'M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z' }],
];

/**
 * Explicit registry rather than `import * as icons from 'lucide'`.
 *
 * The wildcard import pulls all ~1,600 icons into the bundle; naming the 106
 * this app actually uses keeps the icon payload proportional.
 */
export const ICONS = {
  Activity,
  AlertCircle,
  AlertTriangle,
  ArrowDownRight,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BarChart3,
  BookOpen,
  Brain,
  BrainCircuit,
  Briefcase,
  Building,
  Building2,
  Calendar,
  CalendarDays,
  Check,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  ClipboardCheck,
  ClipboardList,
  Clock,
  Code2,
  Compass,
  CreditCard,
  Crown,
  Database,
  Download,
  Edit,
  Edit3,
  Eye,
  FileCheck,
  FileSearch,
  FileSpreadsheet,
  FileText,
  Filter,
  Folder,
  Globe,
  GraduationCap,
  Grid3X3,
  Headset,
  HelpCircle,
  History,
  Home,
  Inbox,
  Info,
  Key,
  Languages,
  LayoutDashboard,
  LayoutGrid,
  Lightbulb,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Minus,
  Moon,
  Network,
  Percent,
  PieChart,
  Play,
  Plus,
  PlusCircle,
  Printer,
  Quote,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  Search,
  Send,
  Settings2,
  Share2,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sparkles,
  Star,
  Sun,
  Tag,
  Target,
  Timer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Trophy,
  Upload,
  User,
  UserCheck,
  UserCircle,
  UserPlus,
  Users,
  Wand2,
  X,
  XCircle,
  Zap,
  Facebook,
  Github,
  Linkedin,
  Twitter,
} as const;

export type IconName = keyof typeof ICONS;
